// Commit Shield git hooks — install / uninstall / detect.
//
// The stakes here are asymmetric. Failing to install our hook costs a user one
// unscanned commit; DESTROYING their husky / lint-staged / pre-commit-framework
// hook costs them their whole CI contract, silently. So most of these tests are
// about what we must NOT do: never clobber a foreign hook, never leave a
// half-valid script behind on uninstall, never wedge git when Termpolis is gone.
//
// Everything is dependency-injected — no real filesystem, no real shell.
import { describe, it, expect } from 'vitest'
import { join } from 'path'
import {
  renderHook,
  installHooks,
  uninstallHooks,
  hookStatus,
  type HookDeps,
  type HookPaths,
} from '../../src/main/gitHooks'

const BEGIN = '# >>> termpolis commit shield >>>'
const END = '# <<< termpolis commit shield <<<'

/** An in-memory hooks dir. Records every write/chmod/remove so tests can assert
 *  on what was touched — and, just as importantly, on what was NOT. */
function fakeFs(seed: Record<string, string> = {}) {
  const files = new Map<string, string>(Object.entries(seed))
  const modes = new Map<string, number>()
  const removed: string[] = []
  const wrote: string[] = []
  const deps: HookDeps = {
    readFile: (p) => (files.has(p) ? (files.get(p) as string) : null),
    writeFile: (p, data) => { files.set(p, data); wrote.push(p) },
    exists: (p) => files.has(p),
    chmod: (p, mode) => { modes.set(p, mode) },
    remove: (p) => { files.delete(p); removed.push(p) },
  }
  return { deps, files, modes, removed, wrote }
}

// Windows paths, with the space that breaks every naive hook generator.
const PATHS: HookPaths = {
  hooksDir: '/repo/.git/hooks',
  nodePath: 'C:\\Program Files\\nodejs\\node.exe',
  scriptPath: 'C:\\Program Files\\Termpolis\\resources\\mcp-adapter\\termpolis-githook.cjs',
}
const PRE_COMMIT = join(PATHS.hooksDir, 'pre-commit')
const PRE_PUSH = join(PATHS.hooksDir, 'pre-push')

// A textbook husky hook: bash shebang, a source line, a gating command.
const HUSKY = [
  '#!/usr/bin/env bash',
  '. "$(dirname -- "$0")/_/husky.sh"',
  '',
  'npx lint-staged || exit 1',
  'echo "lint ok"',
  '',
].join('\n')

// pre-commit.com generates a PYTHON hook. sh code injected into it is not a
// comment — it is a SyntaxError, i.e. a wedged repo.
const PYTHON_HOOK = [
  '#!/usr/bin/env python3',
  '# File generated by pre-commit: https://pre-commit.com',
  'import sys',
  'sys.exit(main())',
  '',
].join('\n')

const countOccurrences = (hay: string, needle: string) => hay.split(needle).length - 1

describe('renderHook — the script text', () => {
  it('is a POSIX sh script (Git for Windows runs hooks through sh)', () => {
    const out = renderHook('pre-commit', PATHS)
    expect(out.startsWith('#!/bin/sh\n')).toBe(true)
    // A stray CR turns every line into `command not found` under MSYS sh.
    expect(out).not.toContain('\r')
  })

  it('wraps our lines in the sentinel block', () => {
    const out = renderHook('pre-push', PATHS)
    expect(out).toContain(BEGIN)
    expect(out).toContain(END)
    expect(out.indexOf(BEGIN)).toBeLessThan(out.indexOf(END))
  })

  it('carries the node path, the scanner path, and the mode arg', () => {
    const posix: HookPaths = {
      hooksDir: '/repo/.git/hooks',
      nodePath: '/usr/local/bin/node',
      scriptPath: '/opt/Termpolis/resources/mcp-adapter/termpolis-githook.cjs',
    }
    const out = renderHook('pre-commit', posix)
    expect(out).toContain('/usr/local/bin/node')
    expect(out).toContain('/opt/Termpolis/resources/mcp-adapter/termpolis-githook.cjs')
    expect(out).toContain('pre-commit')
    expect(out).not.toContain('pre-push')
  })

  it('passes the hook name to the scanner as the mode arg', () => {
    expect(renderHook('pre-push', PATHS)).toMatch(/"\$_termpolis_shield" pre-push/)
    expect(renderHook('pre-commit', PATHS)).toMatch(/"\$_termpolis_shield" pre-commit/)
  })

  it('single-quotes paths that contain spaces', () => {
    const out = renderHook('pre-commit', PATHS)
    expect(out).toContain("'C:/Program Files/nodejs/node.exe'")
    expect(out).toContain("'C:/Program Files/Termpolis/resources/mcp-adapter/termpolis-githook.cjs'")
    // and every expansion of them is double-quoted at the point of use
    expect(out).not.toMatch(/\[ -x \$_termpolis_node \]/)
    expect(out).toContain('[ -x "$_termpolis_node" ]')
  })

  it('normalises Windows backslashes to forward slashes', () => {
    // MSYS sh treats a backslash path as interpreter-dependent at best; forward
    // slashes are accepted by Windows APIs and by every other platform.
    const out = renderHook('pre-commit', PATHS)
    expect(out).not.toContain('C:\\Program Files')
    expect(out).toContain('C:/Program Files')
  })

  it("escapes a single quote in a path (C:\\Users\\O'Brien)", () => {
    const out = renderHook('pre-commit', {
      ...PATHS,
      nodePath: "C:\\Users\\O'Brien\\node.exe",
    })
    expect(out).toContain("'C:/Users/O'\\''Brien/node.exe'")
  })

  it('FAILS OPEN when node is missing', () => {
    const out = renderHook('pre-commit', PATHS)
    expect(out).toContain('[ -x "$_termpolis_node" ] || return 0')
  })

  it('FAILS OPEN when the scanner is gone (Termpolis uninstalled)', () => {
    const out = renderHook('pre-push', PATHS)
    expect(out).toContain('[ -f "$_termpolis_shield" ] || return 0')
  })

  it('FAILS OPEN when node cannot be executed (126 / 127)', () => {
    const out = renderHook('pre-commit', PATHS)
    expect(out).toContain('-eq 126')
    expect(out).toContain('-eq 127')
  })

  it('falls back to node on PATH before giving up', () => {
    // nvm / a node upgrade moves the baked path. Without this the shield would
    // silently switch itself off forever, which is the worst possible failure.
    expect(renderHook('pre-commit', PATHS)).toContain('command -v node')
  })

  it("lets the SCANNER's exit code be what blocks the commit", () => {
    const out = renderHook('pre-commit', PATHS)
    expect(out).toContain('return "$_termpolis_code"')
    expect(out).toContain('termpolis_commit_shield || exit 1')
  })

  it('never exits 0 from inside the block (that would skip a chained hook)', () => {
    for (const line of renderHook('pre-commit', PATHS).split('\n')) {
      expect(line.trim()).not.toBe('exit 0')
    }
  })

  it('namespaces every variable it leaks into a chained script', () => {
    const out = renderHook('pre-commit', PATHS)
    // Our block runs in the SAME shell as any foreign hook below it. A bare
    // NODE= / code= would silently overwrite the user's variable.
    const assigned = [...out.matchAll(/^\s*([A-Za-z_][A-Za-z0-9_]*)=/gm)].map((m) => m[1])
    expect(assigned.length).toBeGreaterThan(0)
    for (const name of assigned) expect(name.startsWith('_termpolis_')).toBe(true)
  })

  it('leaves stdin alone (a chained pre-push still needs its ref list)', () => {
    // git feeds pre-push the refs being pushed on STDIN. If we redirected or
    // drained it, a husky pre-push chained below us would read EOF and pass
    // everything. Redirecting stderr is fine; stdin must stay untouched.
    const out = renderHook('pre-push', PATHS)
    expect(out).not.toContain('</dev/null')
    expect(out).not.toContain('< /dev/null')
    expect(out).not.toContain('| "$_termpolis_node"')
  })
})

describe('installHooks — empty hooks dir', () => {
  it('writes both hooks, executable', () => {
    const fs = fakeFs()
    const written = installHooks(PATHS, fs.deps)
    expect(written).toEqual(['pre-commit', 'pre-push'])
    expect(fs.files.get(PRE_COMMIT)).toBe(renderHook('pre-commit', PATHS))
    expect(fs.files.get(PRE_PUSH)).toBe(renderHook('pre-push', PATHS))
    expect(fs.modes.get(PRE_COMMIT)).toBe(0o755)
    expect(fs.modes.get(PRE_PUSH)).toBe(0o755)
  })

  it('is idempotent — installing twice is byte-identical, with ONE block', () => {
    const fs = fakeFs()
    installHooks(PATHS, fs.deps)
    const first = fs.files.get(PRE_COMMIT) as string
    installHooks(PATHS, fs.deps)
    const second = fs.files.get(PRE_COMMIT) as string
    expect(second).toBe(first)
    expect(countOccurrences(second, BEGIN)).toBe(1)
    expect(countOccurrences(second, END)).toBe(1)
  })

  it('rewrites an in-place block when the node path moves (upgrade, not append)', () => {
    const fs = fakeFs()
    installHooks(PATHS, fs.deps)
    const moved = { ...PATHS, nodePath: 'C:\\nvm\\v22\\node.exe' }
    installHooks(moved, fs.deps)
    const out = fs.files.get(PRE_COMMIT) as string
    expect(countOccurrences(out, BEGIN)).toBe(1)
    expect(out).toContain('C:/nvm/v22/node.exe')
    expect(out).not.toContain('C:/Program Files/nodejs/node.exe')
  })
})

describe('installHooks — a FOREIGN hook is already there', () => {
  it('preserves the husky hook and chains to it', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    const written = installHooks(PATHS, fs.deps)
    expect(written).toEqual(['pre-commit', 'pre-push'])
    const out = fs.files.get(PRE_COMMIT) as string

    // their shebang still owns the file (husky's bash-isms must keep bash)
    expect(out.startsWith('#!/usr/bin/env bash\n')).toBe(true)
    // their command survives...
    expect(out).toContain('npx lint-staged || exit 1')
    expect(out).toContain('. "$(dirname -- "$0")/_/husky.sh"')
    // ...and it still GATES: their body is the verbatim tail of the file, so
    // its exit code is the hook's exit code by fall-through.
    const foreignBody = HUSKY.slice(HUSKY.indexOf('\n') + 1)
    expect(out.endsWith(foreignBody)).toBe(true)
    // we run FIRST, then delegate: block sits between shebang and their code
    expect(out.indexOf(BEGIN)).toBeGreaterThan(0)
    expect(out.indexOf(END)).toBeGreaterThan(out.indexOf(BEGIN))
    expect(out.indexOf('npx lint-staged')).toBeGreaterThan(out.indexOf(END))
    expect(fs.modes.get(PRE_COMMIT)).toBe(0o755)
  })

  it('is idempotent when chained too', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    installHooks(PATHS, fs.deps)
    const first = fs.files.get(PRE_COMMIT) as string
    installHooks(PATHS, fs.deps)
    expect(fs.files.get(PRE_COMMIT)).toBe(first)
    expect(countOccurrences(first, BEGIN)).toBe(1)
    expect(countOccurrences(first, 'npx lint-staged')).toBe(1)
  })

  it('chains a hook that has no shebang at all', () => {
    const bare = 'make verify\n'
    const fs = fakeFs({ [PRE_PUSH]: bare })
    installHooks(PATHS, fs.deps)
    const out = fs.files.get(PRE_PUSH) as string
    expect(out.startsWith(BEGIN)).toBe(true)
    expect(out.endsWith(bare)).toBe(true)
  })

  it('does not rewrite the line endings of a CRLF hook', () => {
    const crlf = '#!/bin/sh\r\nnpm test\r\n'
    const fs = fakeFs({ [PRE_COMMIT]: crlf })
    installHooks(PATHS, fs.deps)
    const out = fs.files.get(PRE_COMMIT) as string
    expect(out).toContain('#!/bin/sh\r\n')
    expect(out).toContain('npm test\r\n')
    expect(out).toContain(BEGIN + '\n') // ...but OUR lines are always LF
  })

  it('REFUSES to overwrite a hook it cannot READ', () => {
    // EPERM, a binary file, a race. If we cannot read it we do not get to guess what
    // is in it — and writing over it is the exact clobber this module exists to stop.
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    const deps: HookDeps = { ...fs.deps, readFile: (p) => (p === PRE_COMMIT ? null : fs.deps.readFile(p)) }
    const written = installHooks(PATHS, deps)
    expect(written).toEqual(['pre-push'])
    expect(fs.wrote).not.toContain(PRE_COMMIT)
    expect(fs.files.get(PRE_COMMIT)).toBe(HUSKY)
  })

  it('REFUSES to inject sh into a non-shell hook (pre-commit.com python)', () => {
    const fs = fakeFs({ [PRE_COMMIT]: PYTHON_HOOK })
    const written = installHooks(PATHS, fs.deps)
    // pre-commit is skipped entirely rather than corrupted into a SyntaxError
    expect(written).toEqual(['pre-push'])
    expect(fs.files.get(PRE_COMMIT)).toBe(PYTHON_HOOK)
    expect(fs.wrote).not.toContain(PRE_COMMIT)
    expect(fs.modes.has(PRE_COMMIT)).toBe(false)
    // ...and the other hook still installs
    expect(fs.files.get(PRE_PUSH)).toBe(renderHook('pre-push', PATHS))
  })
})

describe('uninstallHooks', () => {
  it('deletes the file when the hook is ours alone', () => {
    const fs = fakeFs()
    installHooks(PATHS, fs.deps)
    const cleaned = uninstallHooks(PATHS, fs.deps)
    expect(cleaned).toEqual(['pre-commit', 'pre-push'])
    expect(fs.removed).toEqual([PRE_COMMIT, PRE_PUSH])
    expect(fs.files.has(PRE_COMMIT)).toBe(false)
    expect(fs.files.has(PRE_PUSH)).toBe(false)
  })

  it('strips ONLY our block from a chained hook — byte-identical round trip', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    installHooks(PATHS, fs.deps)
    const cleaned = uninstallHooks(PATHS, fs.deps)
    expect(cleaned).toContain('pre-commit')
    expect(fs.files.get(PRE_COMMIT)).toBe(HUSKY) // exactly what they had
    expect(fs.removed).not.toContain(PRE_COMMIT) // their hook is NOT deleted
  })

  it('leaves the stripped hook valid and executable', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    installHooks(PATHS, fs.deps)
    uninstallHooks(PATHS, fs.deps)
    const out = fs.files.get(PRE_COMMIT) as string
    expect(out.startsWith('#!/usr/bin/env bash\n')).toBe(true)
    expect(out).not.toContain('termpolis')
    expect(out).toContain('npx lint-staged || exit 1')
    expect(fs.modes.get(PRE_COMMIT)).toBe(0o755)
  })

  it('never touches a hook that was never ours', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY, [PRE_PUSH]: PYTHON_HOOK })
    const cleaned = uninstallHooks(PATHS, fs.deps)
    expect(cleaned).toEqual([])
    expect(fs.removed).toEqual([])
    expect(fs.wrote).toEqual([])
    expect(fs.files.get(PRE_COMMIT)).toBe(HUSKY)
    expect(fs.files.get(PRE_PUSH)).toBe(PYTHON_HOOK)
  })

  it('is a no-op when there is nothing installed', () => {
    const fs = fakeFs()
    expect(uninstallHooks(PATHS, fs.deps)).toEqual([])
    expect(fs.removed).toEqual([])
  })

  it('leaves an unreadable hook alone', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    const deps: HookDeps = { ...fs.deps, readFile: () => null }
    expect(uninstallHooks(PATHS, deps)).toEqual([])
    expect(fs.removed).toEqual([])
    expect(fs.wrote).toEqual([])
    expect(fs.files.get(PRE_COMMIT)).toBe(HUSKY)
  })

  it('is idempotent', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    installHooks(PATHS, fs.deps)
    uninstallHooks(PATHS, fs.deps)
    expect(uninstallHooks(PATHS, fs.deps)).toEqual([])
    expect(fs.files.get(PRE_COMMIT)).toBe(HUSKY)
  })
})

describe('hookStatus', () => {
  it('reports absent for an empty hooks dir', () => {
    const fs = fakeFs()
    expect(hookStatus(PATHS, fs.deps)).toEqual({ 'pre-commit': 'absent', 'pre-push': 'absent' })
  })

  it('reports installed after install', () => {
    const fs = fakeFs()
    installHooks(PATHS, fs.deps)
    expect(hookStatus(PATHS, fs.deps)).toEqual({ 'pre-commit': 'installed', 'pre-push': 'installed' })
  })

  it('reports foreign for a hook that is not ours, per hook', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    expect(hookStatus(PATHS, fs.deps)).toEqual({ 'pre-commit': 'foreign', 'pre-push': 'absent' })
  })

  it('reports installed for a chained hook (our block is present)', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    installHooks(PATHS, fs.deps)
    expect(hookStatus(PATHS, fs.deps)['pre-commit']).toBe('installed')
  })

  it('goes back to foreign after uninstalling a chained hook', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    installHooks(PATHS, fs.deps)
    uninstallHooks(PATHS, fs.deps)
    expect(hookStatus(PATHS, fs.deps)['pre-commit']).toBe('foreign')
  })

  it('stays foreign for a non-shell hook we refused to install into', () => {
    const fs = fakeFs({ [PRE_COMMIT]: PYTHON_HOOK })
    installHooks(PATHS, fs.deps)
    expect(hookStatus(PATHS, fs.deps)['pre-commit']).toBe('foreign')
  })

  it('survives an unreadable hook file without throwing', () => {
    const fs = fakeFs({ [PRE_COMMIT]: HUSKY })
    const deps: HookDeps = { ...fs.deps, readFile: () => null }
    expect(hookStatus(PATHS, deps)['pre-commit']).toBe('foreign')
  })
})
